#!/usr/bin/env php
<?php

use PhpLang\Phack;

$program = array_shift($_SERVER['argv']);

$infile = array_shift($_SERVER['argv']);


if ($infile === null) {
    fwrite(STDERR, "Usage: {$program} filename.php\n\n");
    fwrite(STDERR, "Create and dump AST for filename.php\n");

    exit;
}

if (file_exists(__DIR__ . '/vendor/autoload.php')) {
    require __DIR__ . '/vendor/autoload.php';
} elseif (file_exists(__DIR__ . '/../../autoload.php')) {
    require __DIR__ . '/../../autoload.php';
} else {
    throw new \RuntimeException("Unable to locate vendor/autoload.php");
}

$file = file_get_contents($infile);

print_r(Phack\compileString($file));
